codecov:
  notify:
    require_ci_to_pass: no

ignore:
  - "**/*_test.c*"
  - "**/*_test.h*"
  - "**/*_generated.h"
  - "**/*_pb.cc"
  - "**/*_pb.h"
  - "**/test*/*.c*"
  - "**/test*/*.h*"

comment:
  layout: "header, diff, flags, components"
